CREATE OR REPLACE DATABASE ac513;

CREATE TABLE IF NOT EXISTS ALUMNOS(
    id INT UNSIGNED AUTO_INCREMENT,
    dni char(9),
    nombre VARCHAR(64) NOT NULL,
    apellidos VARCHAR(64) NOT NULL,
    sexo ENUM ('H', 'M') NOT NULL,
    dirección VARCHAR(128),
    telefono char(12),
    fnac DATE,
    CONSTRAINT PK_ALU PRIMARY KEY (id),
    CONSTRAINT UK_ALU UNIQUE (dni)
);

CREATE TABLE IF NOT EXISTS ASIGNATURAS(
    id INT UNSIGNED AUTO_INCREMENT,
    nombre VARCHAR(64) NOT NULL,
    aula INT DEFAULT 1,
    duracion INT DEFAULT 3,
    CONSTRAINT PK_ASIG PRIMARY KEY (id),
    CONSTRAINT CK_ASIG_AUL CHECK (aula>0 AND aula<11),
    CONSTRAINT CK_ASIG_DUR CHECK (duracion>0 AND 13)
);

CREATE TABLE IF NOT EXISTS NOTAS(
    idAlumno INT UNSIGNED,
    idAsignatura INT UNSIGNED,
    fecha DATE NOT NULL,
    calificacion DECIMAL(3,1) NOT NULL,
    CONSTRAINT PK_NOTAS PRIMARY KEY (idAlumno, idAsignatura),
    CONSTRAINT FK_NOTAS_IDALU FOREIGN KEY (idAlumno) REFERENCES ALUMNOS(id),
    CONSTRAINT FK_NOTAS_IDASI FOREIGN KEY (idAsignatura) REFERENCES ASIGNATURAS(id),
    CONSTRAINT CK_NOTAS_CALI CHECK (calificacion >= 0.0 AND calificacion <= 10.0)
);

ALTER TABLE ALUMNOS RENAME TO ALUMNO;
ALTER TABLE ASIGNATURAS RENAME TO ASIGNATURA;
ALTER TABLE NOTAS RENAME TO NOTA;

ALTER TABLE NOTA ADD recuperacion INT;
ALTER TABLE NOTA ADD CONSTRAINT CK_RECU CHECK (recuperacion>=0 AND recuperacion<=10);

ALTER TABLE ALUMNO MODIFY sexo ENUM('H', 'F', 'I') NOT NULL;

ALTER TABLE NOTA DROP PK_NOTAS;
ALTER TABLE NOTA ADD CONSTRAINT PK_NOTAS PRIMARY KEY(idAlumno,idAsignatura,fecha);

ALTER TABLE NOTA DROP FK_NOTAS_IDALU;
ALTER TABLE NOTA ADD CONSTRAINT FK_NOTAS_IDALU FOREIGN KEY (idAlumno) REFERENCES ALUMNO(id)
    ON DELETE CASCADE;

